export default [
  {
    id: 1,
    title: 'Dbamy o Twój uśmiech',
    initialText: '1111Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti enim eligendi officiis exercitationem ab nostrum explicabo officia quae adipisci, accusantium culpa eveniet eius voluptate. Odit similique corrupti cum sequi quis.',
    allText: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum, nemo ut alias qui cupiditate fugiat maiores harum eius magnam dicta quia illum doloremque vel quod dolorem. Consectetur cupiditate exercitationem aliquam cumque, vel tenetur rem sequi nisi harum molestiae aspernatur quis. Voluptatibus provident aliquam eveniet quos non quod ab reiciendis facilis fugit saepe, consequuntur iste nulla quas cum. Quia a sunt reprehenderit placeat rem impedit repellat tenetur ullam, fugiat corporis facilis quasi laudantium ex debitis soluta, alias veniam, quos delectus dolorem in labore deserunt! Optio quidem, vel, atque possimus corporis praesentium autem repellendus et quaerat accusantium rem quam molestias libero delectus reprehenderit? Qui repellat amet ut error cum accusantium numquam perspiciatis mollitia earum. Soluta delectus pariatur quae officia ratione deleniti eligendi sit aliquid, recusandae adipisci reiciendis fugit beatae sunt ex eveniet aliquam. Sint quidem distinctio veniam doloremque, reiciendis repellat provident, tenetur maxime sunt consequatur dicta quia et officia expedita, eligendi libero. Harum eveniet ipsa eos, et culpa facilis numquam reiciendis natus, optio omnis commodi odit consequatur sit, cumque non laudantium minus illum. Mollitia ut quaerat eum perspiciatis qui illum, doloremque perferendis, totam rem soluta enim optio voluptate. Quis iure quasi eius aperiam veritatis! Error natus impedit ducimus, ea facere eligendi eveniet.'
  },
  {
    id: 2,
    title: 'Wykorzystujemy najnowsze techologie',
    initialText: '2222Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti enim eligendi officiis exercitationem ab nostrum explicabo officia quae adipisci, accusantium culpa eveniet eius voluptate. Odit similique corrupti cum sequi quis.',
    allText: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum, nemo ut alias qui cupiditate fugiat maiores harum eius magnam dicta quia illum doloremque vel quod dolorem. Consectetur cupiditate exercitationem aliquam cumque, vel tenetur rem sequi nisi harum molestiae aspernatur quis. Voluptatibus provident aliquam eveniet quos non quod ab reiciendis facilis fugit saepe, consequuntur iste nulla quas cum. Quia a sunt reprehenderit placeat rem impedit repellat tenetur ullam, fugiat corporis facilis quasi laudantium ex debitis soluta, alias veniam, quos delectus dolorem in labore deserunt! Optio quidem, vel, atque possimus corporis praesentium autem repellendus et quaerat accusantium rem quam molestias libero delectus reprehenderit? Qui repellat amet ut error cum accusantium numquam perspiciatis mollitia earum. Soluta delectus pariatur quae officia ratione deleniti eligendi sit aliquid, recusandae adipisci reiciendis fugit beatae sunt ex eveniet aliquam. Sint quidem distinctio veniam doloremque, reiciendis repellat provident, tenetur maxime sunt consequatur dicta quia et officia expedita, eligendi libero. Harum eveniet ipsa eos, et culpa facilis numquam reiciendis natus, optio omnis commodi odit consequatur sit, cumque non laudantium minus illum. Mollitia ut quaerat eum perspiciatis qui illum, doloremque perferendis, totam rem soluta enim optio voluptate. Quis iure quasi eius aperiam veritatis! Error natus impedit ducimus, ea facere eligendi eveniet.'
  },
  {
    id: 3,
    title: 'Leczymy bezboleśnie',
    initialText: '4444Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti enim eligendi officiis exercitationem ab nostrum explicabo officia quae adipisci, accusantium culpa eveniet eius voluptate. Odit similique corrupti cum sequi quis.',
    allText: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum, nemo ut alias qui cupiditate fugiat maiores harum eius magnam dicta quia illum doloremque vel quod dolorem. Consectetur cupiditate exercitationem aliquam cumque, vel tenetur rem sequi nisi harum molestiae aspernatur quis. Voluptatibus provident aliquam eveniet quos non quod ab reiciendis facilis fugit saepe, consequuntur iste nulla quas cum. Quia a sunt reprehenderit placeat rem impedit repellat tenetur ullam, fugiat corporis facilis quasi laudantium ex debitis soluta, alias veniam, quos delectus dolorem in labore deserunt! Optio quidem, vel, atque possimus corporis praesentium autem repellendus et quaerat accusantium rem quam molestias libero delectus reprehenderit? Qui repellat amet ut error cum accusantium numquam perspiciatis mollitia earum. Soluta delectus pariatur quae officia ratione deleniti eligendi sit aliquid, recusandae adipisci reiciendis fugit beatae sunt ex eveniet aliquam. Sint quidem distinctio veniam doloremque, reiciendis repellat provident, tenetur maxime sunt consequatur dicta quia et officia expedita, eligendi libero. Harum eveniet ipsa eos, et culpa facilis numquam reiciendis natus, optio omnis commodi odit consequatur sit, cumque non laudantium minus illum. Mollitia ut quaerat eum perspiciatis qui illum, doloremque perferendis, totam rem soluta enim optio voluptate. Quis iure quasi eius aperiam veritatis! Error natus impedit ducimus, ea facere eligendi eveniet.'
  },
];